### PR TITLE
Update Guzzle dependency to require 4.x, 5.x or 6.x

### PR DESCRIPTION
**Pull request by thijswitteveen**

### CODE REVIEW

**Comment by ruudy-es** [comment]
+1

**Comment by litzinger** [comment]
Why is Guzzle 4 still being used on this project?

**Comment by dgtlmoon** [comment]
@ek9 any chance of getting this one in? would really help..

**Comment by afurculita** [comment]
@ek9 any news on this?

**Comment by ek9** [comment]
Hello,

First, thank you for the PR and contribution. I could not accept this PR as it required updates to RemoteXDebug Driver that depends on guzzle, which were missing. Today I released 2 new versions of this extension:

- `v3.1.0` - uses `guzzlehttp/guzzle ~4.0||~5.0`. This is legacy support release, mostly for those still stuck with 4.0 or 5.0 for whatever reason. This version will not likely to receive further updates, but can be used for transition period. It is temporarily maintained on `v3.1` branch.
- `v3.2.0` - uses `guzzlehttp/guzzle ~6.0`. This will be maintained and will receive any updates (master branch).

Additionally, as majority seem to not use RemoteXDebug, I am considering making `guzzlehttp/guzzle` dependency more optional. It would be nice if you could provide any feedback on #15 

Closing this as this has been sorted when updating guzzle.

Thank you for feedback and PR.

**Pull request closed without merging**
